source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.3"
gem "sqlite3", "~> 1.7"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
